[package]
name = "music-player-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.music-player-server]
path = "../server"
version = "0.1.5"

[dependencies.music-player-settings]
path = "../settings"
version = "0.1.0"

[dependencies]
tonic = "0.8.1"
