[package]
name = "music-player"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/tsirysndr/music-player"
license = "MIT"
readme = "README.md"
authors = ["Tsiry Sandratraina <tsiry.sndr@aol.com>"]
categories = ["command-line-utilities"]
keywords = ["tokio", "music", "daemon", "streaming", "player"]
description = "An extensible music player daemon written in Rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

[[bin]]
name = "music-player"
path = "src/main.rs"

[dependencies.music-player-server]
path = "server"
version = "0.1.0"

[dependencies.music-player-playback]
path = "playback"
version = "0.1.0"

[dependencies.music-player-scanner]
path = "scanner"
version = "0.1.0"

[dependencies.music-player-entity]
path = "entity"
version = "0.1.0"

[dependencies.music-player-migration]
path = "migration"
version = "0.1.0"

[dependencies.music-player-settings]
path = "settings"
version = "0.1.0"

[dependencies.music-player-storage]
path = "storage"
version = "0.1.0"

[dependencies.music-player-addons]
path = "addons"
version = "0.1.0"

[dependencies.sea-orm-migration]
version = "^0.9.0"
features = [
  # Enable at least one `ASYNC_RUNTIME` and `DATABASE_DRIVER` feature if you want to run migration via CLI.
  # View the list of supported features at https://www.sea-ql.org/SeaORM/docs/install-and-config/database-and-async-runtime.
  # e.g.
  # "runtime-tokio-rustls",  # `ASYNC_RUNTIME` feature
  # "sqlx-postgres",         # `DATABASE_DRIVER` feature
  "runtime-tokio-rustls",
  "sqlx-sqlite",
]

[dependencies]
clap = "3.2.20"
cpal = "0.13.0"
futures-util = "0.3.24"
lazy_static = "1.4.0"
librespot-protocol = "0.4.2"
log = "0.4.17"
parking_lot = "0.12.1"
rand = { version = "0.8.5", features = ["small_rng"] }
rand_distr = "0.4.3"
rb = "0.4.1"
rodio  = { version = "0.15" }
symphonia = { version = "0.5.1", features = ["aac", "alac", "mp3"] }
thiserror = "1.0.34"
tokio = { version = "1.21.0", features = ["full"] }
zerocopy = "0.6.1"
owo-colors = "3.5.0"
config = "0.13.2"
dirs = "4.0.0"
toml = "0.5.9"
serde = "1.0.144"
