[package]
name = "music-player"
version = "0.1.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/tsirysndr/music-player"
license = "MIT"
authors = ["Tsiry Sandratraina <tsiry.sndr@aol.com>"]
categories = ["command-line-utilities"]
keywords = ["tokio", "music", "cli", "daemon", "streaming", "player"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

[lib]
name = "music_player"
path = "src/lib.rs"

[[bin]]
name = "music-player"
path = "src/main.rs"

[dependencies.music-player-server]
path = "server"

[dependencies]
clap = "3.2.20"
cpal = "0.13.0"
futures-util = "0.3.24"
lazy_static = "1.4.0"
librespot-protocol = "0.4.2"
log = "0.4.17"
parking_lot = "0.12.1"
rand = { version = "0.8.5", features = ["small_rng"] }
rand_distr = "0.4.3"
rb = "0.4.1"
rodio  = { version = "0.15" }
symphonia = { version = "0.5.1", features = ["aac", "alac", "mp3"] }
thiserror = "1.0.34"
tokio = { version = "1.21.0", features = ["full"] }
zerocopy = "0.6.1"
owo-colors = "3.5.0"
