[package]
name = "music-player-settings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.13.2"
dirs = "4.0.0"
serde = "1.0.144"
toml = "0.5.9"
