[package]
name = "music-player-graphql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.music-player-settings]
path = "../settings"
version = "0.1.0"

[dependencies]
async-graphql = "4.0.15"
tide = "0.16.0"
async-graphql-tide = "4.0.15"
tokio = { version = "1.21.0", features = ["full"] }
